FROM node:14-alpine

WORKDIR /app

# install app dependencies
COPY package.json package-lock.json yarn.lock ./
RUN yarn && yarn global add react-scripts@3.4.1

# add app
COPY . ./

# start app
CMD ["yarn", "start"]