version: "3.3"

services: 
  backend:
    image: strapi/strapi:3.6.8-node14-alpine
    ports: 
      - 1337:1337
    restart: on-failure
    volumes: 
      - ./backend:/srv/app
  frontend:
    image: frontend_aqt
    build: 
      context: ./frontend
      dockerfile: ./docker/dockerfile.prod
    depends_on: 
      - backend
    ports: 
      - 3000:3000
    restart: on-failure
    command: sh -c "yarn && yarn start"