version: "3.3"

services: 
  backend:
    image: backend_AQT
    build: 
      context: ./backend
      dockerfile: ./docker/dockerfile
    ports: 
      - 1337:1337
  frontend:
    image: frontend_AQT
    build: 
      context: ./frontend
      dockerfile: ./docker/dockerfile
    depends_on: 
      - backend
    ports: 
      - 3000:3000
    volumes: 
      - ./frontend:.